
code_task:
  description: >
    You will create a game that will run for a long time using Python, following these instructions:

    Instructions
    ____________
    {game}

    IMPORTANT: Your output must be RAW PYTHON CODE ONLY. Do NOT include ```python, ``` or any other markdown formatting.
    Just provide the clean, runnable Python code with no delimiters whatsoever.
  expected_output: >
    IMPORTANT: Your output MUST CONTAIN ONLY PYTHON CODE. DO NOT USE MARKDOWN CODE BLOCKS.
    DO NOT include ```python or ``` in your response. Provide ONLY the raw Python code.
  agent: senior_engineer_agent

review_task:
  description: >
    You will review a game using python, these are the instructions:

    Instructions
    ------------
    {game}

    Using the code you got, check for errors. Check for logic errors,
    syntax errors, missing imports, variable declarations, mismatched brackets,
    and security vulnerabilities.
    
    IMPORTANT: Your output must be RAW PYTHON CODE ONLY. Do NOT include ```python, ``` or any other markdown formatting.
    Just provide the clean, runnable Python code with no delimiters whatsoever.
  expected_output: >
    IMPORTANT: Your output MUST CONTAIN ONLY PYTHON CODE. DO NOT USE MARKDOWN CODE BLOCKS.
    DO NOT include ```python or ``` in your response. Provide ONLY the raw Python code.
  agent: qa_engineer_agent


evaluate_task:
  description: >
    You are helping create a game using python, these are the instructions:

    Instructions
    ------------
    {game}

    You will look over the code to ensure that it is complete and
    does the job that it is supposed to do.
    
    IMPORTANT: Your output must be RAW PYTHON CODE ONLY. Do NOT include ```python, ``` or any other markdown formatting.
    Just provide the clean, runnable Python code with no delimiters whatsoever.
  expected_output: >
    IMPORTANT: Your output MUST CONTAIN ONLY PYTHON CODE. DO NOT USE MARKDOWN CODE BLOCKS.
    DO NOT include ```python or ``` in your response. Provide ONLY the raw Python code.
  agent: chief_qa_engineer_agent